name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - run: |
          wget https://github.com/ElegantLaTeX/ElegantBook/archive/refs/tags/v4.1.zip -o elegantbook.zip
          unzip elegantbook.zip
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            problem/problem.tex
            solution/solution.tex
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./problem:./solution:./elegantbook//"
