name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Xelatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            problem/problem.tex
            solution/solution.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
        env:
          TEXINPUTS: "./problem:./solution"
      - name: Xelatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            problem/problem.tex
            solution/solution.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Xelatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            problem/problem.tex
            solution/solution.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload to release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            problem/problem.tex
            solution/solution.tex
