name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            tlmgr install elegantbook
            latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error problem/problem.tex
            latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error solution/solution.tex
      - name: Upload to release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            problem/problem.tex
            solution/solution.tex
