name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - run: wget https://github.com/ElegantLaTeX/ElegantBook/blob/dev/elegantbook.cls
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        env:
          TEXINPUTS: ".:./problem"
        with:
          latexmk_use_xelatex: true
          root_file: |
            problem/problem.tex
